# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: dasdom
email: 
description: >- # this means to ignore newlines until "baseurl:"
  A blog about iOS development, Objective-C and Swift.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dasdom.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dasdom
github_username:  dasdom

twitter:
    username: dasdom
    card: summary

# Build settings
markdown: kramdown
theme: minima
#theme: texture
#theme: plainwhite
#theme:      tale
#remote_theme: thelehhman/texture
#remote_theme: thelehhman/plainwhite-jekyll
#remote_theme: chesterhow/tale
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

header_pages:
  - imprint.md
  - privacy.md
  - books.md
  - about.md
show_excerpts: true

#plainwhite:
#texture:
#  title: dasdom
#  tagline: A blog about iOS development
#  showNav: true
#  style: black
mimima:
  social-links:
    twitter: dasdom
    github: dasdom
    instagram: swiftandpainless

permalink: /:title/
paginate: 5
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-minimal